### ISSUE TITLE
Multi-arch support specially arm64

### ISSUE THREAD

**Issue by farhad-ris** [jwilder/dockerize#176]
Is it possible to add [multi-arch support](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) specially ARM compatibility so we can benefit from [AWS Graviton](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/), and faster dev on Apple Silicon Macs

**Comment by ezintz** [comment]
I've just forked the repository and integrated a GitHub workflow for multi-platform build. Feel free to try it out yourself https://hub.docker.com/r/ezintz/dockerize/tags.

Tried it for a couple of images and it worked just fine.

**Comment by blimmer** [comment]
I ran into this and was able to get rid of `dockerize` by using the built-in `docker-compose` `healthcheck` and `depends_on` configurations.

## Previous Config

```yaml
version: "3.1"
services:
  db:
    build:
      context: .
      dockerfile: ./db.dockerfile
    ports:
      - 5434:5432

  db-wait:
    image: jwilder/dockerize
    command: dockerize -wait tcp://db:5432 -timeout 1m
    depends_on:
      - db
```

And if I wanted to wait for the db I'd do:

```
docker-compose up db-wait
```

### New Config

Instead, I can now do:

```yaml
version: "3.1"
services:
  db:
    build:
      context: .
      dockerfile: ./db.dockerfile
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
```

and:

```
docker-compose up --wait db
```

For me, this was better than trying to figure out how to keep using `dockerize`.

## Resources

- [This sample repo](https://github.com/peter-evans/docker-compose-healthcheck) has some good code to reference.
- [Compose Specification docs](https://docs.docker.com/compose/compose-file/)
