### ISSUE TITLE
Env vars from linked service are not resolved in Docker Compose v2

### ISSUE THREAD

**Issue by ismarslomic** [jwilder/dockerize#63]
I'm using Dockerize v0.2.0 and after I switched from Docker Compose v1 to v2 I realised that environment variables from linked services are not resolved during container startup.

**Dockerfile**
```
FROM alpine:latest
......
# Install Dockerize
ENV DOCKERIZE_VERSION=0.2.0

RUN wget https://github.com/jwilder/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz \
	&& rm dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz \
	&& mkdir /etc/uchiwa

# Copy template file to image
COPY config.tmpl /etc/uchiwa/

# Run dockerize on template file and start uchiwa
CMD dockerize -template /etc/uchiwa/config.tmpl:/etc/uchiwa/config.json \
  godep go run uchiwa.go -c /etc/uchiwa/config.json
```

**docker-compose.yml**

```
version: '2'
services:
   sensu-api:
    build: 'sensu-api'
    environment:
      - API_PASS=slomic
      - API_USER=ismar
    links:
      - rabbitmq
      - redis
    restart: always

  uchiwa:
    build: 'uchiwa'
    environment:
      - HTTP_PASS=slomic
      - HTTP_USER=ismar
      - UCHIWA_LOG_LEVEL=warn
    links:
      - sensu-api
    ports:
      - '3000:80'
    restart: always
```

**config.tmpl**

```
{
    "sensu":[
        {
            "name": "{{ .Env.SENSU_NAME }}",
            "host": "{{ .Env.SENSU_API_PORT_4567_TCP_ADDR }}",
            "port": {{ .Env.SENSU_API_PORT_4567_TCP_PORT }},
            "user": "{{ .Env.SENSU_API_ENV_API_USER }}",
            "pass": "{{ .Env.SENSU_API_ENV_API_PASS }}"
        }
    ],
    "uchiwa":{
        "host": "{{ default .Env.UCHIWA_HOST "0.0.0.0" }}",
        "port": {{ default .Env.UCHIWA_PORT 80 }},
        "loglevel": "{{ default .Env.UCHIWA_LOG_LEVEL "info" }}",
        "refresh": {{ default .Env.UCHIWA_REFRESH 5 }},
        "user": "{{ .Env.HTTP_USER }}",
        "pass": "{{ .Env.HTTP_PASS }}"
    }
}
```

**config.json** (result after dockerize)

```
{
    "sensu":[
        {
            "name": "Sensu",
            "host": "<no value>",
            "port": <no value>,
            "user": "<no value>",
            "pass": "<no value>"
        }
    ],
    "uchiwa":{
        "host": "0.0.0.0",
        "port": 80,
        "loglevel": "warn",
        "refresh": 5,
        "user": "ismar",
        "pass": "slomic"
    }
}
```
When running same configuration with Docker Compose v1 I get following **config.json** as result:
```
{
    "sensu":[
        {
            "name": "Sensu",
            "host": "172.17.0.10",
            "port": 4567,
            "user": "ismar",
            "pass": "slomic"
        }
    ],
    "uchiwa":{
        "host": "0.0.0.0",
        "port": 80,
        "loglevel": "warn",
        "refresh": 5,
        "user": "ismar",
        "pass": "slomic"
    }
}
```
