### ISSUE TITLE
Can I set interval for `-wait`?

### ISSUE THREAD

**Issue by narfdotpl** [jwilder/dockerize#80]
Hello,

Is it possible to set an interval so that `dockerize -wait` would make requests less frequently? I have a service that has an expensive status check. `dockerize` is spamming the status endpoint, significantly slowing down the startup process. I would like to query the service less frequently, for example every five seconds:

```
$ dockerize -wait http://web:80/status -interval 5s -timeout 120s
```

Thanks! ✌️

**Comment by sivabudh** [comment]
The exact same question I'm here for. :)

**Comment by sivabudh** [comment]
Actually, I dug into the source code, and I think it's "not possible" (at the moment anyway). 5 second was hardcoded.

See:
![dockerize_dockerize_go_at_master_ _jwilder_dockerize](https://cloud.githubusercontent.com/assets/618729/23668560/14d9a3a2-0394-11e7-806c-0b1c00662a40.png)

**Comment by pjakubczyk** [comment]
@sivabudh it's only for `tcp` connections. `http(s)` option hasn't got such sleep.

**Comment by jwilder** [comment]
Ugh.  HTTP(s) should have a delay if it fails.  Adding flag to control how much it waits is pretty straightforward.

**Comment by sivabudh** [comment]
For what it's worth, I replaced `dockerize` completely by using docker-compose version 2.1 `healthcheck` feature instead.

Ref: http://stackoverflow.com/a/41854997/65313

Something like this:

```
version: '2.1'
services:
  some_service:
    ...
    depends_on:
      another_service:
        condition: service_healthy
  another_service:
    ...
    healthcheck:
      test: curl -f http://another_service:<another_servicer_port_number>
      interval: 1s
      timeout: 1s
      retries: 10
```
